/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        grass: '#9DD091',
        fire: '#F29091',
        water: '#91BFF7',
        bug: '#C8D088',
        normal: '#CFCFCF',
        poison: '#C89EE5',
        electric: '#FCDF7F',
        ground: '#C8A78C',
        fairy: '#F6B7F7',
        fighting: '#FFBF7F',
        psychic: '#F69EBC',
        dragon: '#A6AFF0',
        flying: '#C0DCF7',
        rock: '#D7D4C0',
        steel: '#AFD0DB',
        ice: '#9DEBFF',
        ghost: '#B79EB7'
      },
      backgroundImage: {
        'fondo': 'url("/src/img/wallpaperPokeball.jpg")',
        'pokemon-grass-poison': 'linear-gradient(90deg, #9DD091 20%, #C89EE5 80%)',
        'pokemon-fire-flying': 'linear-gradient(90deg, #F29091 20%, #C0DCF7 80%)',
        'pokemon-bug-flying': 'linear-gradient(90deg, #C8D088 20%, #C0DCF7 80%)',
        'pokemon-bug-poison': 'linear-gradient(90deg, #C8D088 20%, #C89EE5 80%)',
        'pokemon-normal-flying': 'linear-gradient(90deg, #CFCFCF 20%, #C0DCF7 80%)',
        'pokemon-poison-ground': 'linear-gradient(90deg, #C89EE5 20%, #C8A78C 80%)',
        'pokemon-normal-fairy': 'linear-gradient(90deg, #CFCFCF 20%, #F6B7F7 80%)',
        'pokemon-poison-flying': 'linear-gradient(90deg, #C89EE5 20%, #C0DCF7 80%)',
        'pokemon-bug-grass': 'linear-gradient(90deg, #C8D088 20%, #9DD091 80%)',
        'pokemon-water-fighting': 'linear-gradient(90deg, #91BFF7 20%, #FFBF7F 80%)',
        'pokemon-water-poison': 'linear-gradient(90deg, #91BFF7 20%, #C89EE5 80%)',
        'pokemon-rock-ground': 'linear-gradient(90deg, #D7D4C0 20%, #C8A78C 80%)',
        'pokemon-water-psychic': 'linear-gradient(90deg, #91BFF7 20%, #F69EBC 80%)',
        'pokemon-electric-steel': 'linear-gradient(90deg, #FCDF7F 20%, #AFD0DB 80%)',
        'pokemon-water-ice': 'linear-gradient(90deg, #91BFF7 20%, #9DEBFF 80%)',
        'pokemon-ghost-poison': 'linear-gradient(90deg, #B79EB7 20%, #C89EE5 80%)',
        'pokemon-grass-psychic': 'linear-gradient(90deg, #9DD091 20%, #F69EBC 80%)',
        'pokemon-ground-rock': 'linear-gradient(90deg, #C8A78C 20%, #D7D4C0 80%)',
        'pokemon-water-psychic': 'linear-gradient(90deg, #91BFF7 20%, #F69EBC 80%)',
        'pokemon-psychic-fairy': 'linear-gradient(90deg, #F69EBC 20%, #F6B7F7 80%)',
        'pokemon-ice-psychic': 'linear-gradient(90deg, #9DEBFF 20%, #F69EBC 80%)',
        'pokemon-water-flying': 'linear-gradient(90deg, #91BFF7 20%, #C0DCF7 80%)',
        'pokemon-rock-water': 'linear-gradient(90deg, #D7D4C0 20%, #91BFF7 80%)',
        'pokemon-rock-flying': 'linear-gradient(90deg, #D7D4C0 20%, #C0DCF7 80%)',
        'pokemon-ice-flying': 'linear-gradient(90deg, #9DEBFF 20%, #C0DCF7 80%)',
        'pokemon-electric-flying': 'linear-gradient(90deg, #FCDF7F 20%, #C0DCF7 80%)',
        'pokemon-dragon-flying': 'linear-gradient(90deg, #A6AFF0 20%, #C0DCF7 80%)',
      }
    }
  },
  safelist: [
    'bg-pokemon-grass-poison',
    'bg-pokemon-fire-flying',
    'bg-pokemon-bug-flying',
    'bg-pokemon-bug-poison',
    'bg-pokemon-normal-flying',
    'bg-pokemon-poison-ground',
    'bg-pokemon-normal-fairy',
    'bg-pokemon-poison-flying',
    'bg-pokemon-bug-grass',
    'bg-pokemon-water-fighting',
    'bg-pokemon-water-poison',
    'bg-pokemon-rock-ground',
    'bg-pokemon-water-psychic',
    'bg-pokemon-electric-steel',
    'bg-pokemon-water-ice',
    'bg-pokemon-ghost-poison',
    'bg-pokemon-grass-psychic',
    'bg-pokemon-ground-rock',
    'bg-pokemon-water-psychic',
    'bg-pokemon-psychic-fairy',
    'bg-pokemon-ice-psychic',
    'bg-pokemon-water-flying',
    'bg-pokemon-rock-water',
    'bg-pokemon-rock-flying',
    'bg-pokemon-ice-flying',
    'bg-pokemon-electric-flying',
    'bg-pokemon-dragon-flying',
  ],
  plugins: [],
}
